sudo: required
services:
  - docker
before_install:
  - docker build -t jorakhachatryan/client-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true jorakhachatryan/client-test npm run test

after_success:
  - docker build -t jorakhachatryan/multi-client  ./client
  - docker build -t jorakhachatryan/multi-nginx  ./nginx
  - docker build -t jorakhachatryan/multi-server  ./server
  - docker build -t jorakhachatryan/multi-worker  ./worker
  # Login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Pushing to docker hub
  - docker push jorakhachatryan/multi-client
  - docker push jorakhachatryan/multi-nginx
  - docker push jorakhachatryan/multi-server
  - docker push jorakhachatryan/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-container-app
  env: MultiContainerApp-env
  bucket_name: "elasticbeanstalk-us-east-2-287663536973"
  bucket_path: "multiple-container-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
